spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/level_up
    username: root
    password: 123456
    #password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false

file:
  dir: C:\hana\study\springboot_project\springboot\src\main\webapp\img\document\